server:
#修改项目tomcat默认端口
  port: 8444
  #context-path 默认是 /  在此处修改为 /don
  servlet:
    context-path: /don

spring:
  profiles:
    active: dev

  don:
    name: 张三
    age: 18
    sex: 男
    info-url: www.baidu.com